# Generated by Django 4.2.6 on 2023-10-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
