# Generated by Django 4.2.6 on 2023-10-20 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSiteApp', '0002_book_total_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='total_rental',
            new_name='total_renta',
        ),
    ]
